name = "woo-worker-backend"
main = "worker.js"
compatibility_date = "2024-01-01"

FCM_PROJECT_ID = "wooadmin-87190"
FCM_CLIENT_EMAIL = "firebase-adminsdk-fbsvc@wooadmin-87190.iam.gserviceaccount.com"
FCM_PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDRDczUCRfJlce+sMQwmjJyaRuaPq21/LCTYOUhHuBpBgKu75pAfPXNGbNWepZMFGIpUCPt5w+07jXTBQ4hix8V4Hozc0xqWvbBVUQesmnqDnRy7tabBu3EIW8XbhxLIXAEKn2GTzCzweWBNneAKipPIYGc+Z5659Ct8lRc7GIHdSN/6EW9lhHUhT3DvE6jWufb1lG3wOlN4slz/0MMm7HC3u3wiwtGeAifXUtpIdIV6mN/4IidyL2Sj42zxN9REkM5iFiH42y0wJlhtXtkkI1/Ojcm8X/nb9eqfnkowlg7/Kp8SX50fxISiiHJD2KnkPkoESJq97hqUlyxdsbFJ3B3AgMBAAECggEAOIG87FFa4yu/to0MMsDzQtajVeF8TdU0G1oVBQtWCD1OK1/rd2PvgtVgEs+G4aCe2eDmHU+YAMVkuhnDNJDowZ6QGWkgbh0RVrfH9m4uT8xBcLGbQ4MvcJTC9PfX4Pz0TMP5cvzjwqr18KO60GNVVVdOtBIK4tjXILWAVS+13aKwatLwnVS84v5MnUuViXbSLd5WkbpCye6OGNRj4nS636QVvHBe8WKQtQV5mPclgi3zF+UbqItXtIDzsulAtbNFi/CSMioXHYHTnhdfgU47rBPU7nscUhIBlNacq0EosPIy2+BoKoKM8Tap7AyjQczffAojrods1XjULDAgN4WfCQKBgQDun+1n7L3c2AyP3PxCTfoZWUx1K2jnsaKUOxzhFS4SPwRMEi6i5Q2om5NBuFVFBh0GU0Ptq4nOeRnixLu/CrZ2VCK3GxJUzjtkA9eZlD9bb328ZZcisXGboYlrS3f5xE+/fowYR33Q4OZtMB3614psGrk367kuc8hM3XIh3kPMTwKBgQDgRqjTmD9k8nuW9y+ShYokmCozfLPaJ7d3zTilvvjWFeafHYFGanvS5wkSxFkp9M65xit4rgGRz3dMPEWlnnKWM5loecwYqjysxdoo0Xv6txdQW4NZ66v/FMEJPewrCIYY0qRNt8sbFsBESs94F9GGSGtKzIsiLnijdr6G8vzHWQKBgQDSaPqxtLMF1QvenwFghdmOGIuulYR/KMcu5aDlaAOj2yUy3qV4xXhxwBzsylmF74oQVcOEAsoU4fvNVaQnJI8Xb8DcrGZRmTgNTMYDihED0x+PzBSkZsrCbIH7tiQofM3FERT/I6rxUB5fERqeYQiRok7H3HcBWt63yFwnORGXSQKBgGd987YAkXBhvMpDMn6ohMCyPvcXWl8W6MCtwLArWeRgotVV5iu6Q31lA3jXhlWoFCUB31mG4k6IsAJL5c+xOCs7kFT3r0jKdck8W5luYYmmJ2n7cLdz2yCQUSuUmYCaJFccDJmYcG8Fpp9c7jP6ucL/dBNGJAYX769uwii/xAmxAoGBAKc9jCjqxO7dWJQ5KNcjFTQYOw7IEB5bTf6AD/+si7fIHSEiwWQ3u9ggJFhbNTmcdXAlr7DQYSi7HQcKuKu0AzulJWwSog6YohQ2QOH/v9711FrlElCJLPp2veEpOStdhgqkqpxwGfNlxG4ZmiO/s06HTbSVw6fa0igasrQNs9wH-----END PRIVATE KEY-----"""



[[kv_namespaces]]
binding = "TOKENS"
id = "217fa154a36443c4b9c34d61c72c1c44"

[[d1_databases]]
binding = "DB"
database_name = "woo_admin"
database_id = "cfbc71c8-a294-41e6-bf76-eceae3f8049b"