name = "woo-worker-backend"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
WOO_URL = "https://socloth.in/"
WOO_CK = "ck_92203ce79bbb4e6713a0c8ba4491cdcd20ce3e83"
WOO_CS = "cs_af346877fb6f478d291d59087c6b44464ab8cfb0"

FCM_PROJECT_ID = "wooadmin-87190"
FCM_CLIENT_EMAIL = "firebase-adminsdk-fbsvc@wooadmin-87190.iam.gserviceaccount.com"


FCM_PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDRDczUCRfJlce+\nsMQwmjJyaRuaPq21/LCTYOUhHuBpBgKu75pAfPXNGbNWepZMFGIpUCPt5w+07jXT\nBQ4hix8V4Hozc0xqWvbBVUQesmnqDnRy7tabBu3EIW8XbhxLIXAEKn2GTzCzweWB\nNneAKipPIYGc+Z5659Ct8lRc7GIHdSN/6EW9lhHUhT3DvE6jWufb1lG3wOlN4slz\n/0MMm7HC3u3wiwtGeAifXUtpIdIV6mN/4IidyL2Sj42zxN9REkM5iFiH42y0wJlh\ntXtkkI1/Ojcm8X/nb9eqfnkowlg7/Kp8SX50fxISiiHJD2KnkPkoESJq97hqUlyx\ndsbFJ3B3AgMBAAECggEAOIG87FFa4yu/to0MMsDzQtajVeF8TdU0G1oVBQtWCD1O\nK1/rd2PvgtVgEs+G4aCe2eDmHU+YAMVkuhnDNJDowZ6QGWkgbh0RVrfH9m4uT8xB\ncLGbQ4MvcJTC9PfX4Pz0TMP5cvzjwqr18KO60GNVVVdOtBIK4tjXILWAVS+13aKw\natLwnVS84v5MnUuViXbSLd5WkbpCye6OGNRj4nS636QVvHBe8WKQtQV5mPclgi3z\nF+UbqItXtIDzsulAtbNFi/CSMioXHYHTnhdfgU47rBPU7nscUhIBlNacq0EosPIy\n2+BoKoKM8Tap7AyjQczffAojrods1XjULDAgN4WfCQKBgQDun+1n7L3c2AyP3PxC\nTfoZWUx1K2jnsaKUOxzhFS4SPwRMEi6i5Q2om5NBuFVFBh0GU0Ptq4nOeRnixLu/\nCrZ2VCK3GxJUzjtkA9eZlD9bb328ZZcisXGboYlrS3f5xE+/fowYR33Q4OZtMB36\n14psGrk367kuc8hM3XIh3kPMTwKBgQDgRqjTmD9k8nuW9y+ShYokmCozfLPaJ7d3\nzTilvvjWFeafHYFGanvS5wkSxFkp9M65xit4rgGRz3dMPEWlnnKWM5loecwYqjys\nxdoo0Xv6txdQW4NZ66v/FMEJPewrCIYY0qRNt8sbFsBESs94F9GGSGtKzIsiLnij\ndr6G8vzHWQKBgQDSaPqxtLMF1QvenwFghdmOGIuulYR/KMcu5aDlaAOj2yUy3qV4\nxXhxwBzsylmF74oQVcOEAsoU4fvNVaQnJI8Xb8DcrGZRmTgNTMYDihED0x+PzBSk\nZsrCbIH7tiQofM3FERT/I6rxUB5fERqeYQiRok7H3HcBWt63yFwnORGXSQKBgGd9\n87YAkXBhvMpDMn6ohMCyPvcXWl8W6MCtwLArWeRgotVV5iu6Q31lA3jXhlWoFCUB\n31mG4k6IsAJL5c+xOCs7kFT3r0jKdck8W5luYYmmJ2n7cLdz2yCQUSuUmYCaJFcc\nDJmYcG8Fpp9c7jP6ucL/dBNGJAYX769uwii/xAmxAoGBAKc9jCjqxO7dWJQ5KNcj\nFTQYOw7IEB5bTf6AD/+si7fIHSEiwWQ3u9ggJFhbNTmcdXAlr7DQYSi7HQcKuKu0\nAzulJWwSog6YohQ2QOH/v9711FrlElCJLPp2veEpOStdhgqkqpxwGfNlxG4ZmiO/\ns06HTbSVw6fa0igasrQNs9wH\n-----END PRIVATE KEY-----\n"""


[[kv_namespaces]]
binding = "TOKENS"
id = "217fa154a36443c4b9c34d61c72c1c44"
